//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Road2Work.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_user
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Mdp { get; set; }
        public bool Est_admin { get; set; }
    
        public virtual T_information T_information { get; set; }
    }
}
